### CRIE UMA CLASSE CARRO E DECLARE 3 TIPOS DE CARROS DIFERENTES COM AS SEGUINTES DESCRIÇÕES
### CARRO1 | CARRO2 E CARRO3
## TERÃO NOME, COR E ANO_DE_FABRICACAO


### CONFIGURE A FUNÇÃO DE CADASTRO DE LIVROS, PARA CADASTAR LIVROS EM ARQUIVOS TXT E CHAME NA
## FUNÇÃO MAIN PARA TESTAR


## enconding="utf-8".


print("Aprendendo o GitHub")